// Code generated by MockGen. DO NOT EDIT.
// Source: usecase/port/todo_input_port.go

// Package mock_port is a generated GoMock package.
package mock_port

import (
	port "gin-todo-sample/usecase/port"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockTodoInputPort is a mock of TodoInputPort interface
type MockTodoInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockTodoInputPortMockRecorder
}

// MockTodoInputPortMockRecorder is the mock recorder for MockTodoInputPort
type MockTodoInputPortMockRecorder struct {
	mock *MockTodoInputPort
}

// NewMockTodoInputPort creates a new mock instance
func NewMockTodoInputPort(ctrl *gomock.Controller) *MockTodoInputPort {
	mock := &MockTodoInputPort{ctrl: ctrl}
	mock.recorder = &MockTodoInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockTodoInputPort) EXPECT() *MockTodoInputPortMockRecorder {
	return m.recorder
}

// Get mocks base method
func (m *MockTodoInputPort) Get(arg0 *port.GetTodoRequest) (*port.GetTodoResponse, port.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(*port.GetTodoResponse)
	ret1, _ := ret[1].(port.Error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockTodoInputPortMockRecorder) Get(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTodoInputPort)(nil).Get), arg0)
}
